// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AccessibilityController from "./accessibility_controller.js"
application.register("accessibility", AccessibilityController)

import Analytics__EventsController from "./analytics/events_controller.js"
application.register("analytics--events", Analytics__EventsController)

import Analytics__PageViewsController from "./analytics/page_views_controller.js"
application.register("analytics--page-views", Analytics__PageViewsController)

import JavascriptEnabledController from "./javascript_enabled_controller.js"
application.register("javascript-enabled", JavascriptEnabledController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import DropdownPillController from "./dropdown_pill_controller.js"
application.register("dropdown-pill", DropdownPillController)

import FileUploadController from "./file_upload_controller.js"
application.register("file-upload", FileUploadController)

import Forms__AutosubmitController from "./forms/autosubmit_controller.js"
application.register("forms--autosubmit", Forms__AutosubmitController)

import Forms__KeyboardSubmitController from "./forms/keyboard_submit_controller.js"
application.register("forms--keyboard-submit", Forms__KeyboardSubmitController)

import KeyboardShortcutController from "./keyboard_shortcut_controller.js"
application.register("keyboard-shortcut", KeyboardShortcutController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import PageScrollController from "./page_scroll_controller.js"
application.register("page-scroll", PageScrollController)

import ToggleController from "./toggle_controller.js"
application.register("toggle", ToggleController)

import TurboNative__InAppPurchasesController from "./turbo_native/in_app_purchases_controller.js"
application.register("turbo-native--in-app-purchases", TurboNative__InAppPurchasesController)

import TurboNative__SignOutController from "./turbo_native/sign_out_controller.js"
application.register("turbo-native--sign-out", TurboNative__SignOutController)
