// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import FileUploadController from "./file_upload_controller.js"
application.register("file-upload", FileUploadController)

import GoalsController from "./goals_controller.js"
application.register("goals", GoalsController)

import PaginationController from "./pagination_controller.js"
application.register("pagination", PaginationController)
